<?php

namespace Collectif\LoggerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteLoggerRepository extends EntityRepository
{
}
