collectif_gallery:
    resource: "@CollectifGalleryBundle/Resources/config/routing.yml"
    prefix:   /

collectif_logger:
    resource: "@CollectifLoggerBundle/Resources/config/routing.yml"
    prefix:   /

collectif_statistics:
    resource: "@CollectifStatisticsBundle/Resources/config/routing.yml"
    prefix:   /

collectif_front:
    resource: "@CollectifFrontBundle/Resources/config/routing.yml"
    prefix:   /

collectif_membre:
    resource: "@CollectifAdminBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /reseau

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /reseau/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
