<?php

namespace Collectif\StatisticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends EntityRepository
{
	public function getStatistics($user)
	{
		return $this->createQueryBuilder('s')
		->select('COUNT(s)')
		->where('s.membre = :user')
		->setParameter('user', $user)
		->getQuery()
		->getSingleScalarResult();
	}
	
	public function getUniqueStatistics($user)
	{
		return $this->createQueryBuilder('s')
		->select('COUNT(DISTINCT s.ip)')
		->where('s.membre = :user')
		->setParameter('user', $user)
		->getQuery()
		->getSingleScalarResult();
	
		/*$qb->where('s.membre = :user')
		->setParameter('user', $user)
		->gr;
	
		return $qb->getQuery()->getResult();*/
	}
}
