parameters:
#    collectif_statistics.example.class: Collectif\StatisticsBundle\Example

services:
#    collectif_statistics.example:
#        class: %collectif_statistics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
