reseau_sousforum:
    pattern:  /
    defaults: { _controller: "CollectifAdminBundle:SousForum:index" }

reseau_sousforum_show:
    pattern:  /{id}/show
    defaults: { _controller: "CollectifAdminBundle:SousForum:show" }

reseau_sousforum_new:
    pattern:  /new/{type}
    defaults: { _controller: "CollectifAdminBundle:SousForum:new" }

reseau_sousforum_create:
    pattern:  /create/{type}
    defaults: { _controller: "CollectifAdminBundle:SousForum:create" }
    requirements: { _method: post }
    
reseau_sousforum_create_post:
    pattern:  /createpost/{sfId}
    defaults: { _controller: "CollectifAdminBundle:SousForum:createPost" }
    requirements: { _method: post }

reseau_sousforum_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CollectifAdminBundle:SousForum:edit" }

reseau_sousforum_update:
    pattern:  /{id}/update
    defaults: { _controller: "CollectifAdminBundle:SousForum:update" }
    requirements: { _method: post }

reseau_sousforum_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CollectifAdminBundle:SousForum:delete" }

reseau_sousforum_before_new:
    pattern:  /before/new
    defaults: { _controller: "CollectifAdminBundle:SousForum:before" }
    
reseau_sousforum_create_message:
    pattern:  /createmessage/{sfId}
    defaults: { _controller: "CollectifAdminBundle:SousForum:createMessage" }
    requirements: { _method: post }

reseau_sousforum_message_show:
    pattern:  /{id}/message/show
    defaults: { _controller: "CollectifAdminBundle:SousForum:showMessage" }
    
reseau_sousforum_delete_message:
    pattern:  /{id}/deleteMessage
    defaults: { _controller: "CollectifAdminBundle:SousForum:deleteMessage" }

reseau_sousforum_delete_post:
    pattern:  /{id}/deletePost
    defaults: { _controller: "CollectifAdminBundle:SousForum:deletePost" }