<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticles($actif, $limit=null)
	{
	    $qb = $this->createQueryBuilder('a');

	    $qb->where('a.actif = :actif')
	         ->setParameter('actif', $actif)
	       ->orderBy('a.dateModification', 'DESC')
		   ->setMaxResults( $limit );
	
	    return $qb->getQuery()->getResult();
	}
	
	public function getArticlesPublications()
	{
		$string = "SELECT titre, resume, contenu, dateModification FROM CollectifAdminBundle:Article UNION SELECT titre, resume, contenu, dateModification FROM CollectifAdminBundle:Publication order by dateModification DESC";
		$query = $this->_em->createQuery($string);

		$resultats = $query->getResult();

    	return $resultats;
	}
	
	public function getArticlesSearch($arg="")
	{
		$qb = $this->createQueryBuilder('a');
	
		$qb->where('a.titre like :arg OR a.contenu like :arg')
		->setParameter('arg', "%".$arg."%");
	
		return $qb->getQuery()->getResult();
	}
}
