<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends EntityRepository
{
	public function getPending($pending)
	{
		$params = array(
			'pending', $pending
		);
		//$qb = $this->createQueryBuilder();
		
		return $this->getEntityManager()->createQuery('SELECT c FROM CollectifAdminBundle:Candidature c JOIN c.membre m WHERE c.pending = '.$pending.' AND m.enabled = false ORDER BY c.id DESC')->getResult();
		/*
		$qb->select('c')
    	->from('Candidature', 'c')
    	->join('c.membre', 'm')
    	->where('c.pending = :pending')
    	->andWhere('m.enabled = false')
      	->setParameters($params)
		->orderBy('c.id', 'DESC');

		return $qb->getQuery()->getResult();*/
	}
	
	public function getByUser($userId)
	{
		$qb = $this->createQueryBuilder('c');
	
		$qb->where('c.membre = :membre')
		->setParameter('membre', $userId);
		
		$resultats = $qb->getQuery()->getResult();
		
		if(sizeof($resultats) > 0)
			return $resultats[0];
		else 
			return null;
	}
	
}
