<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends EntityRepository
{
	public function getPending($pending)
	{
		$qb = $this->createQueryBuilder('c');
	
		$qb->where('c.pending = :pending')
		->setParameter('pending', $pending)
		->orderBy('c.id', 'DESC');
	
		return $qb->getQuery()->getResult();
	}
	
}
