<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends EntityRepository
{
	
	public function getAll()
	{
	    $qb = $this->createQueryBuilder('d');

	    $qb->orderBy('d.ordre', 'ASC');
	
	    return $qb->getQuery()->getResult();
	}
	
    public function getDomaines($actif)
	{
	    $qb = $this->createQueryBuilder('d');

	    $qb->where('d.actif = :actif')
	         ->setParameter('actif', $actif)
	       ->orderBy('d.ordre', 'ASC');
	
	    return $qb->getQuery()->getResult();
	}
	
	public function getMaxOrdre()
	{
		$query = $this->_em->createQuery('SELECT MAX(d.ordre) FROM CollectifAdminBundle:Domaine d');
    	$resultats = $query->getSingleResult();

    	return $resultats[1];
	}
	
	
	public function getDomaineByTitre($titre)
	{
	    $qb = $this->createQueryBuilder('d');

	    $qb->where('d.titrePage = :titre')
	         ->setParameter('titre', $titre);
	
	    return $qb->getQuery()->getSingleResult();
	}
	
	
	public function getDomainesSearch($arg="")
	{
		$qb = $this->createQueryBuilder('d');
		
		$qb->where('d.nom like :arg OR d.description like :arg')
		->setParameter('arg', "%".$arg."%");
		
		return $qb->getQuery()->getResult();
	}
}
