<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonCvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonCvRepository extends EntityRepository
{
	public function getCvFR($userId)
	{
		$qb = $this->createQueryBuilder('cv');
	
		$qb->where('cv.membre = :userId')
		->setParameter('userId', $userId);
	
		return $qb->getQuery()->getResult();
	}
}
