<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
	public function getPublicationsByUser($userId)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.membre = :user')
		->setParameter('user', $userId);
		
		return $qb->getQuery()->getResult();
	}
	
	public function getPublicationsSearch($arg="")
	{
		$qb = $this->createQueryBuilder('a');
	
		$qb->where('a.titre like :arg OR a.contenu like :arg')
		->setParameter('arg', "%".$arg."%");
	
		return $qb->getQuery()->getResult();
	}
	
	public function findByAlias($alias)
	{
		$qb = $this->createQueryBuilder('p');
	
		$qb->where('p.alias = :alias')
		->setParameter('alias', $alias);
	
		return $qb->getQuery()->getSingleResult();
	}
}
