<?php

namespace Collectif\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
	public function getPublicationsByUser($userId)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.membre = :user')
		->setParameter('user', $userId);
		
		return $qb->getQuery()->getResult();
	}
}
