parameters:
#    collectif_front.example.class: Collectif\FrontBundle\Example

services:
#    collectif_front.example:
#        class: %collectif_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
